name: Build Windows

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - uses: Jimver/cuda-toolkit@v0.2.30
        id: cuda-toolkit
      - name: Install dependencies with choco and vcpkg
        run: |
          choco install -y wget pkgconfiglite --no-progress
          C:\vcpkg\vcpkg.exe install cairo[core]:x64-windows-static
      - name: Install OneAPI
        run: |
          wget -q https://registrationcenter-download.intel.com/akdlm/IRC_NAS/df5b2d7b-050a-447b-87e7-c870c7c5d552/intel-cpp-essentials-2025.3.0.326_offline.exe
          intel-cpp-essentials-2025.3.0.326_offline.exe -a --silent --eula accept --install-dir D:\a\LightwaveExplorer\intel\oneapi
        shell: cmd
      - name: Install Qt
        uses: jurplel/install-qt-action@v4.3.0
      - name: Build LightwaveExplorer
        run: |
          call "D:\a\LightwaveExplorer\intel\oneapi\setvars.bat"
          cmake -E make_directory build
          cd build
          cmake -DMAKEDEPENDENCIES=1 .. -G "Visual Studio 17 2022" -A x64
          cmake --build . --config Release
          cmake --fresh -DMAKESYCL=1 .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -T "Intel(R) oneAPI DPC++ Compiler 2025"
          cmake --build . --config Release
          cmake --fresh .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="x64-windows-static" -DPKG_CONFIG_PATH="C:/vcpkg/installed/x64-windows-static/lib/pkgconfig" -DCMAKE_CUDA_ARCHITECTURES="75;86;89;90;120"
          cmake --build . --config Release
        shell: cmd
      - name: Clean up distribution folder
        run: |
          cd build
          Remove-Item .\Release\*.exp -Force
          Remove-Item .\Release\*.lib
          Copy-Item -Path Release -Destination LightwaveExplorerWin64 -Recurse
          7z a -tzip LightwaveExplorerWin64.zip LightwaveExplorerWin64\*
      - name: upload-unsigned-artifact
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/LightwaveExplorerWin64
      - name: submit-signing-request
        id: submit-signing-request
        uses: signpath/github-action-submit-signing-request@v2
        with:
          api-token: "${{ secrets.SIGNPATH_API_TOKEN }}"
          organization-id: "783ed34a-91fc-4bc6-9142-da97f921e9ee"
          project-slug: "LightwaveExplorer"
          signing-policy-slug: "test-signing"
          github-artifact-id: "${{ steps.upload-unsigned-artifact.outputs.artifact-id }}"
          wait-for-completion: true
          output-artifact-directory: "build/LightwaveExplorer_signed"
        if: ${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}
      - name: upload-signed-artifact
        uses: actions/upload-artifact@v4
        with:
          name: LightwaveExplorer_Win64_signed
          path: build/LightwaveExplorer_signed
        if: ${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}
      - name: Upload to Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/LightwaveExplorer_signed/LightwaveExplorer_Win64_signed.zip
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        if: ${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}
