name: Build Windows

on:
  push:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Jimver/cuda-toolkit@v0.2.24
        id: cuda-toolkit
      - run: |
          choco install -y wget pkgconfiglite --no-progress
      - run: |
          wget -q https://registrationcenter-download.intel.com/akdlm/IRC_NAS/f5881e61-dcdc-40f1-9bd9-717081ac623c/intel-oneapi-base-toolkit-2025.2.1.46_offline.exe
          .\intel-oneapi-base-toolkit-2025.2.1.46_offline.exe -a --eula accept
      - run: |
          C:\vcpkg\vcpkg.exe install dlib[core]:x64-windows miniz:x64-windows gcem:x64-windows
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
      - run: |
          call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
          cmake -E make_directory build
          cd build
          cmake -DMAKESYCL=1 .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -T "Intel(R) oneAPI DPC++ Compiler 2025"
          cmake --build . --config Release

          cmake --fresh .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_CUDA_ARCHITECTURES="75;86"
          cmake --build . --config Release
        shell: cmd
      - run: |
          xcopy /s /y Release LightwaveExplorerWin64
          del /f /q LightwaveExplorerWin64\LightwaveExplorerSYCL.exp
          del /f /q LightwaveExplorerWin64\LightwaveExplorerSYCL.lib

          7z a -tzip LightwaveExplorerWin64.zip LightwaveExplorerWin64\*
